[theme]
base = "dark"

# General color setup
textColor = "rgb(217, 218, 232)"
primaryColor = "rgb(85, 85, 222)"

backgroundColor = "rgb(24, 28, 54)"
secondaryBackgroundColor = "rgb(24, 28, 54)"
sidebar.backgroundColor = "rgb(9, 16, 44)"


# Widgets
showWidgetBorder = true
borderColor = "rgb(59, 80, 106)"

# Dataframes
dataframeHeaderBackgroundColor = "rgb(31, 37, 70)"  

# Base text
font = "'Space Grotesk':https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap"
# font = "'IBM Plex Sans KR':https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR&display=swap"
baseFontWeight = 400
baseFontSize = 16


# Heading text
headingFont = "Space Grotesk"
headingFontWeights = [400, 400, 300, 300, 300, 300]
headingFontSizes = ["1.8rem", "1.5rem", "1.2rem"]

